In [9]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver import ActionChains
from selenium.webdriver.support import expected_conditions as EC
import time
import re


driver = webdriver.Chrome()
driver.get("https://www.redbus.in/")
driver.maximize_window()
time.sleep(5)

wait = WebDriverWait(driver, 10)
try:
     state_bus = wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR,"a[href='https://www.redbus.in/online-booking/rtc-directory']")))
     actions = ActionChains(driver)
     actions.move_to_element(state_bus).perform()
     print("Successfully Moved")
     time.sleep(2)
     state_bus.click()

except Exception as e:
    print("Class Not Located",e)

driver.switch_to.window(driver.window_handles[1])

try:
    bus_available = wait.until(EC.element_to_be_clickable((By.XPATH, "//a[@class='D113_link' and text()='APSRTC']")))
    actions = ActionChains(driver)
    actions.move_to_element(bus_available).perform()
    print("Successfully Moved")
    time.sleep(2)
    bus_available.click()
    time.sleep(2)
    bus_details = wait.until(EC.element_to_be_clickable((By.CLASS_NAME, "route"))).click()
    # bus_details.click()
    time.sleep(10)
    gvt_bus = wait.until(EC.presence_of_all_elements_located((By.XPATH, "//div[@class='button' and text()='View Buses']")))
    for button in reversed(gvt_bus):
        button.click()
    
except Exception as e:
    print("data not Scrapped")

try:
    bulk_list = []
    busname=[]
    bustype = []
    departing_time = []
    duration = []
    reaching_time = []
    star_rating = []
    price = []
    seats_available = []
    last_height = driver.execute_script("return document.body.scrollHeight")
    print(last_height)
    scrolling = True
    while scrolling:
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")

        time.sleep(3)

        new_height = driver.execute_script("return document.body.scrollHeight")
        if new_height == last_height:
            break
        last_height = new_height

    bus_name_details = wait.until(EC.presence_of_all_elements_located((By.XPATH, "//div[@class='travels lh-24 f-bold d-color']")))
    # bustype_details = wait.until(EC.presence_of_all_elements_located((By.XPATH, "//div[@class='bus-type f-12 m-top-16 l-color evBus']")))
    bustype_details = wait.until(EC.presence_of_all_elements_located((By.CSS_SELECTOR, ".bus-type.f-12.m-top-16.l-color.evBus")))
    departing_time_details = wait.until(EC.presence_of_all_elements_located((By.CSS_SELECTOR, ".dp-time.f-19.d-color.f-bold")))
    reaching_time_details = wait.until(EC.presence_of_all_elements_located((By.CSS_SELECTOR, ".bp-time.f-19.d-color.disp-Inline")))
    duration_details = wait.until(EC.presence_of_all_elements_located((By.XPATH, "//div[@class='dur l-color lh-24']")))
    star_rating_details = wait.until(EC.presence_of_all_elements_located((By.CSS_SELECTOR, "div.rating-sec.lh-24")))
    price_details = wait.until(EC.presence_of_all_elements_located((By.CSS_SELECTOR, "div.seat-fare")))
    seats_available_details = wait.until(EC.presence_of_all_elements_located((By.CSS_SELECTOR, "div.column-eight.w-15.fl")))

    for i in bus_name_details:
        busname.append(i.text)

    for i in bustype_details:
        bustype.append(i.text)
    
    for i in departing_time_details:
        departing_time.append(i.text)

    for i in reaching_time_details:
        reaching_time.append(i.text)

    for i in duration_details:
        duration.append(i.text)    

    for i in star_rating_details:
        star_rating.append(i.text)

    for i in price_details:
        price.append(i.text)

    for i in seats_available_details:
        seats_available.append(i.text)    

except Exception as e:
    print(f"An ERROR Occured : {e}")


seats = [int(i.split()[0]) for i in seats_available]
final_price = [int(re.findall(r'\d+',i)[0]) for i in price]

# bulk_list.append(bus_)
bulk_list.append(busname)
bulk_list.append(bustype)
bulk_list.append(departing_time)
bulk_list.append(reaching_time)
bulk_list.append(duration)
bulk_list.append(star_rating)
bulk_list.append(final_price)
bulk_list.append(seats)

for i in bulk_list:
    print(type(i))
print(bulk_list, type(bulk_list))

Successfully Moved
Successfully Moved
11071

TypeError: int() argument must be a string, a bytes-like object or a real number, not 'list'

In [7]:
import re
for i in range(len(bulk_list)):
    print(bulk_list[i])
# print(bulk_list[6])
# final_price = [int(re.findall(r'\d+',i)[0]) for i in price]
# print(final_price)

['TSRTC - 1637', 'TSRTC - 41331', 'TSRTC - 41310', 'TSRTC - 1450', 'TSRTC - 7770', 'TSRTC - 41562', 'TSRTC - 13762', 'TSRTC - 41531', 'TSRTC - 41762', 'TSRTC - 1049', 'TSRTC - 7742', 'TSRTC - 14562', 'TSRTC - 7774', 'TSRTC - 9883', 'TSRTC - 1404', 'TSRTC - 31162', 'TSRTC - 1917', 'TSRTC - 40377', 'TSRTC - 30510', 'TSRTC - 41962', 'TSRTC - 14762', 'TSRTC - 1824', 'TSRTC - 1594', 'TSRTC - 9885', 'TSRTC - 1616', 'TSRTC - 41731', 'TSRTC - 16362', 'TSRTC - 1586', 'TSRTC - 7762', 'APSRTC - 9651', 'APSRTC - 4046', 'APSRTC - 35179', 'APSRTC - 40568', 'APSRTC - 4048', 'APSRTC - 3908', 'APSRTC - 35155', 'APSRTC - 3575', 'APSRTC - 35265', 'APSRTC - 3910', 'APSRTC - 3633', 'APSRTC - 35063', 'APSRTC - 3838', 'APSRTC - 4350', 'APSRTC - 3609', 'APSRTC - 3968', 'APSRTC - 3888', 'APSRTC - 3569', 'APSRTC - 3533', 'APSRTC - 4790', 'APSRTC - 3545', 'APSRTC - 4178', 'APSRTC - 4369', 'APSRTC - 3057', 'APSRTC - 3535', 'APSRTC - 4995', 'FRESHBUS', 'IntrCity SmartBus', 'FRESHBUS', 'AdSrivastav Travels', 'GMRK Tours and Travels', 'IntrCity SmartBus', 'IntrCity SmartBus', 'FRESHBUS', 'FRESHBUS', 'IntrCity SmartBus', 'Zingbus Plus', 'IntrCity SmartBus', 'NueGo', 'Svkdt travels', 'NueGo', 'NueGo', 'IntrCity SmartBus', 'Sri KVR Travels', 'NueGo', 'Yolo Bus', 'IntrCity SmartBus', 'Svkdt travels', 'NueGo', 'Pavan Tours and Travels', 'IntrCity SmartBus', 'NueGo', 'Sri Durga Malleswari Travels', 'V Kaveri Travels', 'LVP Travels', 'Shyamoli Paribahan Pvt Ltd', 'Sri Atluri Travels', 'Sudha Sri Tours and Travels', 'Varun Travels', 'Royal Varma Travels', 'Sai Dasari Travels', 'Varun Travels', 'Sai Sri Durga Travels', 'YNR Travels', 'Orange Tours And Travels', 'Anjani Bus', 'Svkdt travels', 'Sri KVR Travels', 'NueGo', 'Morning Star Travels', 'NueGo', 'Orange Tours And Travels', 'Orange Tours And Travels', 'Sri Venkata Padmavathi Travels', 'Orange Tours And Travels', 'Orange Tours And Travels', 'Orange Tours And Travels', 'Nani Svkdt Travels', 'Go Tour Travels and Holidays', 'Orange Tours And Travels', 'SREE KARA TRAVELS', 'Siri Tours and Travels', 'Krk Travels', 'Sri Atluri Travels', 'V Kaveri Travels', 'AVR Travels', 'Moonlight Travels', 'AVR Travels', 'Sri Krishna Travels', 'SS Prasanna Travels', 'Sree Raghavendra Travels', 'Sri Krishna Travels', 'Naveen Tours and Travels', 'VR Travels', 'Orange Tours And Travels', 'Prasanna Travels', 'Navayuga Travels', 'Nani Svkdt Travels', "Vinay's Tours and Travels", 'Sai Dasari Travels', 'Morning Star Travels']
['GARUDA PLUS (VOLVO / BENZ A.C Multi Axle)', 'SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)', 'SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)', 'RAJADHANI AC (CONVERTED METRO LUXURY)', 'SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)', 'SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)', 'eGARUDA', 'SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)', 'SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)', 'RAJDHANI (A.C. Semi Sleeper)', 'SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)', 'eGARUDA', 'Lahari Non A/C Sleeper Cum Seater', 'Lahari Non A/C Sleeper Cum Seater', 'RAJDHANI (A.C. Semi Sleeper)', 'RAJDHANI (A.C. Semi Sleeper)', 'SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)', 'SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)', 'LAHARI A/C SLEEPER CUM SEATER', 'SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)', 'eGARUDA', 'RAJDHANI (A.C. Semi Sleeper)', 'RAJDHANI (A.C. Semi Sleeper)', 'SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)', 'SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)', 'SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)', 'eGARUDA', 'RAJDHANI (A.C. Semi Sleeper)', 'SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)', 'SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)', 'SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)', 'VENNELA (A.C. SLEEPER)', 'SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)', 'SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)', 'SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)', 'AMARAVATHI (VOLVO / SCANIA A.C Multi Axle)', 'AMARAVATHI (VOLVO / SCANIA A.C Multi Axle)', 'VENNELA (A.C. SLEEPER)', 'INDRA(A.C. Seater)', 'AMARAVATHI (VOLVO / SCANIA A.C Multi Axle)', 'SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)', 'VENNELA (A.C. SLEEPER)', 'STAR LINER(NON-AC SLEEPER 2+1)', 'SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)', 'INDRA(A.C. Seater)', 'VENNELA (A.C. SLEEPER)', 'INDRA(A.C. Seater)', 'SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)', 'AMARAVATHI (VOLVO / SCANIA A.C Multi Axle)', 'DOLPHIN CRUISE (VOLVO / SCANIA A.C Multi Axle)', 'AMARAVATHI (VOLVO / SCANIA A.C Multi Axle)', 'INDRA(A.C. Seater)', 'VENNELA (A.C. SLEEPER)', 'VENNELA (A.C. SLEEPER)', 'INDRA(A.C. Seater)', 'Electric A/C Seater (2+2)', 'A/C Seater / Sleeper (2+1)', 'Electric A/C Seater (2+2)', 'Bharat Benz A/C Sleeper (2+1)', 'Volvo A/C Semi Sleeper (2+2)', 'A/C Seater / Sleeper (2+1)', 'A/C Seater / Sleeper (2+1)', 'Electric A/C Seater (2+2)', 'Electric A/C Seater (2+2)', 'A/C Seater / Sleeper (2+1)', 'A/C Seater / Sleeper (2+1)', 'AC Sleeper (2+1)', 'Electric A/C Seater (2+2)', 'A/C Sleeper (2+1)', 'Electric A/C Seater (2+2)', 'Electric A/C Seater (2+2)', 'Scania AC Multi Axle Sleeper (2+1)', 'A/C Sleeper (2+1)', 'Electric A/C Seater/Sleeper (2+1)', 'A/C Seater / Sleeper (2+1)', 'VE A/C Seater / Sleeper (2+1)', 'A/C Sleeper (2+1)', 'Electric A/C Seater/Sleeper (2+1)', 'A/C Sleeper (2+1)', 'AC Sleeper (2+1)', 'Electric A/C Seater (2+2)', 'A/C Sleeper (2+1)', 'A/C Seater / Sleeper (2+1)', 'A/C Seater / Sleeper (2+1)', 'Scania Multi-Axle AC Semi Sleeper (2+2)', 'A/C Seater / Sleeper (2+1)', 'A/C Sleeper (2+1)', 'Scania AC Multi Axle Sleeper (2+1)', 'Non A/C Seater / Sleeper (2+1)', 'NON A/C Hi-Tech Push Back (2+2)', 'Bharat Benz A/C Sleeper (2+1)', 'Non A/C Seater / Sleeper (2+1)', 'A/C Sleeper (2+1)', 'NON A/C Seater/ Sleeper (2+1)', 'A/C Seater / Sleeper (2+1)', 'A/C Seater / Sleeper (2+1)', 'NON A/C Sleeper (2+1)', 'Electric A/C Seater (2+2)', 'A/C Sleeper (2+1)', 'Electric A/C Seater (2+2)', 'Bharat Benz A/C Seater /Sleeper (2+1)', 'Bharat Benz A/C Sleeper (2+1)', 'Non A/C Seater / Sleeper (2+1)', 'Bharat Benz A/C Sleeper (2+1)', 'Volvo Multi-Axle Sleeper A/C (2+1)', 'NON A/C Sleeper (2+1)', 'A/C Sleeper (2+1)', 'A/C Seater / Sleeper (2+1)', 'NON A/C Seater/ Sleeper (2+1)', 'Non A/C Seater / Sleeper (2+1)', 'A/C Seater / Sleeper (2+1)', 'Non A/C Seater / Sleeper (2+1)', 'NON A/C Hi-Tech (2+2)', 'A/C Seater / Sleeper (2+1)', 'A/C Seater / Sleeper (2+1)', 'A/C Sleeper (2+1)', 'A/C Seater (2+2)', 'Volvo Multi-Axle A/C Sleeper (2+1)', 'A/C Seater (2+2)', 'NON A/C Semi Sleeper (2+1)', 'Volvo Multi-Axle A/C Sleeper (2+1)', 'A/C Seater/Sleeper (2+1)', 'Non A/C Seater / Sleeper (2+1)', 'A/C Sleeper (2+1)', 'A/C Seater / Sleeper (2+1)', 'NON AC Seater / Sleeper 2+1', 'A/C Sleeper (2+1)', 'A/C Sleeper (2+1)', 'A/C Sleeper (2+1)', 'Scania AC Multi Axle Sleeper (2+1)']
['20:05', '20:15', '20:35', '20:45', '20:45', '20:55', '21:05', '21:15', '21:35', '21:45', '21:45', '22:05', '22:10', '22:15', '22:25', '22:30', '22:35', '22:35', '22:45', '22:55', '23:05', '23:05', '23:15', '23:15', '23:30', '23:35', '23:35', '23:45', '23:55', '21:00', '21:00', '21:45', '21:53', '22:00', '22:00', '22:00', '22:15', '22:15', '22:30', '22:30', '22:30', '22:45', '22:45', '22:53', '22:55', '23:00', '23:00', '23:00', '23:05', '23:30', '23:40', '23:45', '23:45', '23:50', '00:15', '23:35', '22:50', '22:20', '23:00', '23:40', '23:10', '22:40', '21:20', '23:00', '23:40', '22:20', '23:30', '21:50', '23:20', '22:35', '22:30', '23:10', '23:20', '21:30', '23:33', '22:55', '23:00', '23:00', '23:10', '23:45', '22:45', '22:20', '22:50', '22:43', '23:40', '22:50', '23:10', '23:25', '22:15', '22:50', '22:15', '23:05', '23:55', '22:45', '22:50', '22:10', '21:45', '23:59', '22:40', '23:50', '23:15', '23:30', '22:20', '23:55', '23:15', '23:00', '23:00', '23:20', '00:30', '23:59', '00:04', '23:45', '22:25', '22:40', '22:55', '23:00', '23:30', '22:40', '23:20', '21:10', '23:25', '23:30', '23:59', '23:30', '22:35', '00:25', '23:20', '22:35', '23:50', '22:35']
['01:40', '00:55', '02:30', '02:15', '02:15', '03:00', '03:10', '01:45', '03:50', '02:00', '03:45', '04:10', '03:30', '04:20', '04:00', '05:00', '03:30', '03:20', '04:15', '05:00', '05:10', '03:35', '03:45', '05:20', '04:25', '04:20', '05:40', '04:15', '04:50', '04:41', '03:40', '02:20', '06:00', '04:20', '04:25', '03:42', '04:40', '02:50', '03:05', '04:10', '06:10', '04:20', '04:16', '06:40', '05:05', '03:35', '03:46', '05:25', '05:20', '05:35', '05:35', '05:44', '04:45', '05:25', '05:40', '06:15', '06:25', '05:20', '06:40', '05:55', '05:45', '05:45', '04:05', '05:55', '06:10', '05:40', '06:30', '04:05', '06:14', '05:10', '06:00', '05:55', '05:35', '05:20', '05:43', '05:40', '05:50', '06:30', '05:15', '06:00', '05:57', '05:55', '05:50', '05:30', '06:05', '04:45', '05:47', '05:10', '05:15', '06:10', '04:45', '06:30', '06:00', '05:15', '05:45', '05:40', '05:25', '07:12', '05:50', '07:12', '06:45', '06:15', '06:00', '05:45', '05:45', '05:30', '05:26', '06:00', '07:20', '06:20', '06:17', '07:20', '04:50', '05:55', '05:45', '06:05', '05:30', '06:32', '06:26', '05:30', '06:45', '05:30', '06:10', '06:00', '05:25', '06:41', '05:45', '05:25', '06:10', '04:46']
['05h 35m', '04h 40m', '05h 55m', '05h 30m', '05h 30m', '06h 05m', '06h 05m', '04h 30m', '06h 15m', '04h 15m', '06h 00m', '06h 05m', '05h 20m', '06h 05m', '05h 35m', '06h 30m', '04h 55m', '04h 45m', '05h 30m', '06h 05m', '06h 05m', '04h 30m', '04h 30m', '06h 05m', '04h 55m', '04h 45m', '06h 05m', '04h 30m', '04h 55m', '07h 41m', '06h 40m', '04h 35m', '08h 07m', '06h 20m', '06h 25m', '05h 42m', '06h 25m', '04h 35m', '04h 35m', '05h 40m', '07h 40m', '05h 35m', '05h 31m', '07h 47m', '06h 10m', '04h 35m', '04h 46m', '06h 25m', '06h 15m', '06h 05m', '05h 55m', '05h 59m', '05h 00m', '05h 35m', '05h 25m', '06h 40m', '07h 35m', '07h 00m', '07h 40m', '06h 15m', '06h 35m', '07h 05m', '06h 45m', '06h 55m', '06h 30m', '07h 20m', '07h 00m', '06h 15m', '06h 54m', '06h 35m', '07h 30m', '06h 45m', '06h 15m', '07h 50m', '06h 10m', '06h 45m', '06h 50m', '07h 30m', '06h 05m', '06h 15m', '07h 12m', '07h 35m', '07h 00m', '06h 47m', '06h 25m', '05h 55m', '06h 37m', '05h 45m', '07h 00m', '07h 20m', '06h 30m', '07h 25m', '06h 05m', '06h 30m', '06h 55m', '07h 30m', '07h 40m', '07h 13m', '07h 10m', '07h 22m', '07h 30m', '06h 45m', '07h 40m', '05h 50m', '06h 30m', '06h 30m', '06h 26m', '06h 40m', '06h 50m', '06h 21m', '06h 13m', '07h 35m', '06h 25m', '07h 15m', '06h 50m', '07h 05m', '06h 00m', '751h 52m', '07h 06m', '08h 20m', '07h 20m', '06h 00m', '06h 11m', '06h 30m', '06h 50m', '06h 16m', '06h 25m', '06h 50m', '06h 20m', '06h 11m']
['3.4', '3.7', '4.7', '2.6', '3.4', '3.9', '4.4', '3.5', '3.0', '3.0', '4.4', '3.6', '4.0', '4.1', '3.4', '2.7', '3.7', '3.8', '4.2', '3.9', '4.1', '3.5', '3.5', '3.9', '3.9', '3.9', '4.0', '3.0', '3.7', '4.8', '4.1', '4.6', '4.7', '4.5', '3.8', '4.2', '4.1', '3.8', '3.6', '4.2', '4.7', '3.6', '4.2', '4.3', '2.6', '4.3', '4.3', '4.2', '4.4', '4.5', '4.6', '3.1', '3.5', '3.8', '4.5', '4.3', '4.7', '4.6', '3.5', '4.7', '4.7', '4.6', '4.5', '4.5', '4.5', '4.6', '4.5', '4.3', '4.4', '4.3', '4.2', '4.3', '4.3', '4.2', '4.1', '4.5', '4.1', '4.0', '4.6', '4.3', '4.2', '4.1', '4.0', '4.2', '4.4', '4.2', '4.0', '4.2', '4.6', '4.3', '4.2', '3.4', '3.1', '3.2', '3.9', '3.9', '3.8', '3.8', '3.8', '3.9', '3.4', '3.4', '3.9', '3.4', '3.3', '3.5', '3.5', '3.2', '3.1', '3.8', '3.7', '3.6', '3.6', '3.5', '2.8', '2.4', '1.3', '1.5', '2.6', '1.9', '1.5', '2.8', '2.6', '2.7', '2.6', '2.6', '2.7', '2.0']
[533, 396, 396, 480, 542, 396, 533, 396, 396, 480, 396, 533, 561, 442, 480, 480, 396, 396, 536, 396, 533, 480, 533, 396, 396, 440, 533, 480, 396, 469, 469, 781, 469, 469, 469, 720, 720, 781, 567, 720, 469, 839, 607, 469, 567, 781, 567, 436, 720, 720, 720, 567, 781, 839, 567, 899, 811, 880, 999, 749, 811, 1036, 880, 700, 792, 1176, 1134, 672, 1060, 655, 906, 1348, 1239, 950, 940, 889, 1060, 773, 1171, 1292, 800, 870, 870, 888, 849, 1111, 1090, 1100, 990, 770, 1000, 3000, 4000, 700, 799, 1060, 1222, 980, 1090, 1040, 800, 1200, 750, 1100, 1100, 710, 1099, 1360, 1200, 1333, 1880, 1400, 780, 940, 849, 1300, 799, 1100, 799, 3000, 1100, 3999, 4000, 1100, 860, 999, 1299, 999, 1200, 1090]
['36 Seats available\n16 Window', '30 Seats available', '27 Seats available', '23 Seats available\n8 Window', '11 Seats available', '26 Seats available', '20 Seats available\n9 Window', '29 Seats available', '19 Seats available', '37 Seats available\n18 Window', '24 Seats available', '12 Seats available\n2 Window', '11 Seats available\n3 Single', '12 Seats available\n2 Single', '11 Seats available\n5 Window', '9 Seats available\n4 Window', '2 Seats available', '22 Seats available', '7 Seats available\n1 Window', '6 Seats available', '8 Seats available\n2 Window', '26 Seats available\n13 Window', '18 Seats available\n8 Window', '7 Seats available', '6 Seats available', '31 Seats available', '3 Seats available\n1 Window', '29 Seats available\n13 Window', '19 Seats available', '1 Seat available', '3 Seats available', '11 Seats available\n1 Single', '1 Seat available', '1 Seat available', '2 Seats available', '1 Seat available', '6 Seats available\n2 Window', '11 Seats available\n6 Window', '5 Seats available', '5 Seats available\n2 Window', '2 Seats available', '1 Seat available', '1 Seat available', '1 Seat available', '1 Seat available', '9 Seats available\n2 Single', '2 Seats available', '3 Seats available', '1 Seat available', '2 Seats available', '3 Seats available', '2 Seats available', '11 Seats available\n1 Single', '2 Seats available\n1 Window', '1 Seat available', '12 Seats available\n4 Window', '4 Seats available\n2 Single', '7 Seats available', '15 Seats available\n6 Window', '2 Seats available\n1 Window', '8 Seats available\n3 Single', '1 Seat available', '6 Seats available\n1 Window', '7 Seats available\n3 Window', '10 Seats available\n2 Single', '7 Seats available', '6 Seats available\n5 Window', '1 Seat available', '3 Seats available\n1 Window', '4 Seats available', '1 Seat available', '2 Seats available\n1 Window', '10 Seats available\n1 Single', '1 Seat available', '1 Seat available\n1 Single', '6 Seats available\n1 Window', '3 Seats available', '2 Seats available', '6 Seats available\n1 Single', '6 Seats available\n2 Single', '3 Seats available', '1 Seat available', '1 Seat available', '1 Seat available', '5 Seats available\n1 Window', '2 Seats available', '3 Seats available\n1 Single', '8 Seats available', '2 Seats available', '1 Seat available', '5 Seats available', '40 Seats available\n10 Single', '32 Seats available', '13 Seats available\n5 Window', '1 Seat available', '2 Seats available', '2 Seats available\n1 Window', '1 Seat available', '2 Seats available', '1 Seat available', '4 Seats available\n2 Window', '3 Seats available\n1 Window', '1 Seat available', '6 Seats available\n3 Window', '8 Seats available\n4 Window', '1 Seat available', '5 Seats available\n1 Window', '2 Seats available\n1 Window', '2 Seats available\n1 Window', '3 Seats available', '1 Seat available\n1 Window', '1 Seat available', '1 Seat available', '4 Seats available\n1 Window', '25 Seats available\n3 Single', '16 Seats available\n5 Single', '11 Seats available\n6 Window', '16 Seats available\n1 Single', '25 Seats available\n11 Window', '35 Seats available\n17 Window', '13 Seats available\n2 Single', '44 Seats available', '40 Seats available', '7 Seats available\n3 Window', '2 Seats available\n1 Single', '1 Seat available', '1 Seat available', '2 Seats available', '4 Seats available\n2 Window', '3 Seats available\n1 Single']

In [ ]:
import pandas as pd
header = ['Bus Name', 'Bus Type', 'Departure Time', 'Arrival Time','Duration','Star Rating','Price','Seats Available']
# header = ['Bus Name', 'Bus Type', 'Departure Time', 'Arrival Time','Duration']
df=pd.DataFrame(bulk_list,header)
df = df.T
df.insert(0,'Id',range(1,len(df)+1))
# print(df)
# print(df.head())  # Check the first few rows
# print(df.columns)
df.to_csv('route.csv',index=False)
df.info()
df['Star Rating'].fillna(0.0, inplace=True)
df.info()

In [15]:
from sqlalchemy import create_engine, text, MetaData, Table, Column, Integer, String, Float, Time
engine = create_engine('mysql+pymysql://root:root@localhost')
with engine.connect() as connection:
    connection.execute(text('CREATE DATABASE IF NOT EXISTS RedbusInfo'))
engine = create_engine('mysql+pymysql://root:root@localhost/RedbusInfo')

In [16]:
drop_table_sql = 'DROP TABLE IF EXISTS bus_info;'
with engine.connect() as connection:
    connection.execute(text(drop_table_sql))

In [17]:
create_table_sql = '''
CREATE TABLE IF NOT EXISTS bus_info (
    Id INT,
    `Bus Name` VARCHAR(255),
    `Bus Type` VARCHAR(255),
    `Departure Time` VARCHAR(50),
    `Arrival Time` VARCHAR(50),
    `Star Rating` FLOAT,
    `Duration` VARCHAR(50),
    `Price` INT,
    `Seats Available` INT
) ROW_FORMAT=DYNAMIC;
'''
# Execute the table creation SQL
with engine.connect() as connection:
    connection.execute(text(create_table_sql))

# Insert the data into the pre-created table
df.to_sql('bus_info', con=engine, if_exists='append', index=False)

DataError: (pymysql.err.DataError) (1265, "Data truncated for column 'Seats Available' at row 1")
[SQL: INSERT INTO bus_info (`Id`, `Bus Name`, `Bus Type`, `Departure Time`, `Arrival Time`, `Duration`, `Star Rating`, `Price`, `Seats Available`) VALUES (%(Id)s, %(Bus_Name)s, %(Bus_Type)s, %(Departure_Time)s, %(Arrival_Time)s, %(Duration)s, %(Star_Rating)s, %(Price)s, %(Seats_Available)s)]
[parameters: [{'Id': 1, 'Bus_Name': 'TSRTC - 41931', 'Bus_Type': 'SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)', 'Departure_Time': '04:10', 'Arrival_Time': '09:10', 'Duration': '05h 00m', 'Star_Rating': '4.6', 'Price': 396, 'Seats_Available': '11 Seats available'}, {'Id': 2, 'Bus_Name': 'TSRTC - 1132', 'Bus_Type': 'RAJDHANI (A.C. Semi Sleeper)', 'Departure_Time': '05:30', 'Arrival_Time': '11:20', 'Duration': '05h 50m', 'Star_Rating': '2.9', 'Price': 533, 'Seats_Available': '9 Seats available\n1 Window'}, {'Id': 3, 'Bus_Name': 'TSRTC - 40577', 'Bus_Type': 'SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)', 'Departure_Time': '06:30', 'Arrival_Time': '11:20', 'Duration': '04h 50m', 'Star_Rating': '3.7', 'Price': 396, 'Seats_Available': '10 Seats available'}, {'Id': 4, 'Bus_Name': 'TSRTC - 1959', 'Bus_Type': 'RAJDHANI (A.C. Semi Sleeper)', 'Departure_Time': '06:50', 'Arrival_Time': '12:50', 'Duration': '06h 00m', 'Star_Rating': '3.9', 'Price': 533, 'Seats_Available': '23 Seats available\n9 Window'}, {'Id': 5, 'Bus_Name': 'TSRTC - 2981', 'Bus_Type': 'RAJADHANI AC (CONVERTED METRO LUXURY)', 'Departure_Time': '07:20', 'Arrival_Time': '13:00', 'Duration': '05h 40m', 'Star_Rating': '1.7', 'Price': 480, 'Seats_Available': '21 Seats available\n7 Window'}, {'Id': 6, 'Bus_Name': 'TSRTC - 1596', 'Bus_Type': 'RAJDHANI (A.C. Semi Sleeper)', 'Departure_Time': '07:40', 'Arrival_Time': '12:15', 'Duration': '04h 35m', 'Star_Rating': '1.9', 'Price': 533, 'Seats_Available': '33 Seats available\n16 Window'}, {'Id': 7, 'Bus_Name': 'TSRTC - 7693', 'Bus_Type': 'SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)', 'Departure_Time': '08:00', 'Arrival_Time': '13:20', 'Duration': '05h 20m', 'Star_Rating': '4.0', 'Price': 396, 'Seats_Available': '13 Seats available'}, {'Id': 8, 'Bus_Name': 'TSRTC - 31110', 'Bus_Type': 'RAJDHANI (A.C. Semi Sleeper)', 'Departure_Time': '08:40', 'Arrival_Time': '14:20', 'Duration': '05h 40m', 'Star_Rating': '3.2', 'Price': 480, 'Seats_Available': '23 Seats available\n7 Window'}  ... displaying 10 of 386 total bound parameter sets ...  {'Id': 385, 'Bus_Name': 'Sri Krishna Travels', 'Bus_Type': 'Volvo Multi-Axle A/C Sleeper (2+1)', 'Departure_Time': '23:35', 'Arrival_Time': '06:45', 'Duration': '07h 10m', 'Star_Rating': 0.0, 'Price': 1200, 'Seats_Available': '29 Seats available\n8 Single'}, {'Id': 386, 'Bus_Name': 'Naveen Tours and Travels', 'Bus_Type': 'A/C Seater/Sleeper (2+1)', 'Departure_Time': '23:30', 'Arrival_Time': '05:30', 'Duration': '06h 00m', 'Star_Rating': 0.0, 'Price': 3999, 'Seats_Available': '44 Seats available'}]]
(Background on this error at: https://sqlalche.me/e/20/9h9h)